# This workflow installs dependencies, caches them, builds, tests, and uploads an artifact.
# For details: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (if script exists)
        run: npm run build --if-present

      - name: Zip dist and manifest.json
        uses: vimtor/action-zip@v1.2
        with:
          files: dist/ manifest.json
          dest: result.zip

      - name: Create dummy artifact file
        run: |
          mkdir -p path/to/artifact
          echo "hello" > path/to/artifact/world.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact-${{ github.run_id }}-${{ matrix.node-version }}
          path: path/to/artifact/world.txt
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false
